<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" <?php language_attributes(); ?>>

<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="<?php bloginfo('html_type'); ?>; charset=<?php bloginfo('charset'); ?>" />

<title><?php wp_title('&laquo;', true, 'right'); ?> <?php bloginfo('name'); ?></title>

<link rel="stylesheet" href="<?php bloginfo('stylesheet_url'); ?>" type="text/css" media="screen" />

<?php wp_head(); ?>
</head>
<body class="login">

<div id="header">
	<div id="branding">
	    <div id="blog-title">
		<span><a href="<?php echo get_option('home'); ?>/"><?php bloginfo('name'); ?></a></span>
		</div>
	    <h1 id="blog-description">Login</h1>
	</div>
	<div id="access"></div>
</div>
    Custom login header
<div id="loginform">
<!-- code of the form generated by Wordpress -->